app:
  name: gno-val-01
  role: validator
  type: rpc

storage:
  capacity: 1Gi # 120Gi
  local:
    path: /opt/gnoland/validator/1/data

svc:
  name: gno-val-svc-01
  type: LoadBalancer

ingress:
  enabled: false

placement:
  tolerations:
    enabled: false

### Globals ###
global:
  binaryVersion: master
