app:
  name: gnocore-val-01
  role: validator
  type: rpc

storage:
  capacity: 1Gi # 120Gi
  local:
    path: /opt/gnoland/gnocore-val-01/data

svc:
  name: gnocore-val-01-svc
  type: LoadBalancer

ingress:
  enabled: false

placement:
  tolerations:
    enabled: false

### Globals ###
global:
  binaryVersion: master
