app:
  name: gnocore-rpc-01
  role: validator
  type: rpc

storage:
  capacity: 1Gi
  local:
    path: /opt/gnoland/rpc/1/data

svc:
  name: gnoland-rpc
  type: LoadBalancer

ingress:
  enabled: false

placement:
  tolerations:
    enabled: false

gnoland:
  config:
    rpc:
      laddr: "tcp://0.0.0.0:26657"

### Globals ###
global:
  binaryVersion: master
