name: dagger
on:
  push:
    branches: [master]

jobs:

  test:
    name: sample-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: dagger/dagger-for-github@v8
        with:
          verb: call
          workdir: samples/gnokey
          args: make-tx --home-dir-key=. --password-string=helloworld

  supernova:
    name: supernova-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Supernova Run
        uses: dagger/dagger-for-github@v7
        with:
          version: "v0.16.1"
          verb: call
          workdir: samples/supernova
          args: run-test --sub-accounts 2 --transactions 100
