name: dagger
on:
  push:
    branches: [master]

jobs:

  build-gnoland:
    name: gnoland-build-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Dagger version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@v0.0.2
        with:
          path: daggerverse/gnoland
      - name: Build Gnocontribs
        uses: dagger/dagger-for-github@v8.4.0
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          module: daggerverse/gnoland
          call: build-image-from-source --binary GNOCONTRIBS_BIN

  gnoland-ecosystem:
    name: gnoland-ecosystem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Dagger version
        id: dagger_version
        uses: sagikazarmark/dagger-version-action@v0.0.2
        with:
          path: daggerverse/gnoland
      - name: Build Docs
        uses: dagger/dagger-for-github@v8.4.0
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          module: daggerverse/docs.gno.land
          call: build-doc
      - name: GnoKey MakeTx
        uses: dagger/dagger-for-github@v8.4.0
        with:
          version: ${{ steps.dagger_version.outputs.version }}
          module: daggerverse/gnokey
          call: make-tx --home-dir-key=. --password-string=helloworld

  dagger_helm:
    name: dagger-helm-cli
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dagger-version: ["0.18.14", "0.19.8", latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dagger Run
        uses: dagger/dagger-for-github@v8.4.0
        with:
          varsion: latest
          verb: call
          workdir: daggerverse/kind-dagger
          args: run-dagger-helm --socket=/var/run/docker.sock --dagger-cli-helm ../dagger-helm/ --dagger-version ${{ matrix.dagger-version }}
