name: dagger
on:
  push:
    branches: [master]

jobs:

  build:
    name: gnoland-build-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Gnocontribs
        uses: dagger/dagger-for-github@v8.2.0
        with:
          verb: call
          workdir: daggerverse/gnoland
          args: build-image-from-source --binary GNOCONTRIBS_BIN

  gnokey:
    name: gnokey-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: MakeTx
        uses: dagger/dagger-for-github@v8.2.0
        with:
          verb: call
          workdir: daggerverse/gnokey
          args: make-tx --home-dir-key=. --password-string=helloworld

  supernova:
    name: supernova-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Supernova Run
        uses: dagger/dagger-for-github@v8.2.0
        with:
          verb: call
          workdir: daggerverse/supernova
          args: run-test --sub-accounts 2 --transactions 100
